;; :NOTE: не самое лучшее название, можно base
(defn basa[o] (fn[a b] (mapv o a b)))
(def v+ (basa +))
(def v- (basa -))
(def v* (basa *))
(def vd (basa /))
(def m+ (basa v+))
(def m- (basa v-))
(def m* (basa v*))
(def md (basa vd))
(def c+ (basa m+))
(def c- (basa m-))
(def c* (basa m*))
(def cd (basa md))
(defn v*s [v s](mapv (fn [k] (* k ( * s))) v))
(defn scalar [a b](apply + (v* a b)))
(defn transpose [m] (apply mapv vector m))
(defn m*s [m s] (mapv (fn [x] (v*s x s)) m))
(defn m*v [m v] (mapv (fn [x] (scalar x v)) m))
(defn m*m [m1 m2]((fn [a b] (mapv (fn [k] (m*v (transpose b) k)) a)) m1 m2))
(defn fix [x y a b] (- (* (nth x a) (nth y b)) (* (nth y a) (nth x b))))
(defn vect [v1 v2] ((fn [x y] (vector (fix x y 1 2) (fix x y 2 0) (fix x y 0 1))) v1 v2))