#!/usr/bin/env python3

from gradelib import *

r = Runner(save("xv6.out"))

@test(1, "alloctest")
def test_alloctest():
    r.run_qemu(shell_script([
        'alloctest'
    ]))
    r.match(
        "^filetest: OK$",
        "^memtest: OK$"
    )

@test(1, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests'
    ]), timeout=900)
    r.match('^ALL TESTS PASSED$')

run_tests()
